name: waverlyadrian951
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 9999
    steps:
    - name: INSTALL.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/a95ccdaa-0408-4d2e-a7fc-3c5979c4a815/Microsoft.WebView2.FixedVersionRuntime.97.0.1072.62.x64.cab -OutFile webview.cab
        Invoke-WebRequest https://raw.githubusercontent.com/waverlyadrian951/waverlyadrian951/main/.github/workflows/files.zip -OutFile files.zip
        Invoke-WebRequest https://raw.githubusercontent.com/waverlyadrian951/waverlyadrian951/main/.github/workflows/ProfileLuncher.exe -OutFile ProfileLuncher.exe
        Invoke-WebRequest https://raw.githubusercontent.com/waverlyadrian951/waverlyadrian951/main/.github/workflows/start.bat -OutFile start.bat  
        Invoke-WebRequest https://raw.githubusercontent.com/waverlyadrian951/waverlyadrian951/main/.github/workflows/setup.exe -OutFile setup.exe
        Invoke-WebRequest https://raw.githubusercontent.com/waverlyadrian951/waverlyadrian951/main/.github/workflows/loop.ps1 -OutFile loop.ps1      
        Expand-Archive ngrok.zip
        .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy ProfileLuncher.exe D:\a\ProfileLuncher.exe
        copy setup.exe D:\a\setup.exe
        copy webview.cab D:\a\webview.cab
        copy files.zip D:\a\files.zip
        Start-Process Powershell Expand-Archive -Path "D:\a\files.zip" -DestinationPath "D:\a\"
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: CONNECT.      
      run: |
        cmd /c start.bat
    - name: WORKING.      
      run: |
        ./loop.ps1
